Add support for postgres in `ws db console`

diff --git a/harness/config/commands.yml b/harness/config/commands.yml
--- a/harness/config/commands.yml
+++ b/harness/config/commands.yml
@@ -119,9 +119,21 @@ command('db-console'): |
 command('db console'):
   env:
     COMPOSE_BIN: = @('docker.compose.bin')
+    DB_PLATFORM: = @('database.platform')
   exec: |
     #!bash(workspace:/)|@
-    passthru "$COMPOSE_BIN exec console bash -c 'mysql --host \"\$DB_HOST\" --user \"\$DB_USER\" -p\"\$DB_PASS\" \"\$DB_NAME\"'"
+    case "${DB_PLATFORM}" in
+    mysql)
+      passthru $COMPOSE_BIN exec console bash -c 'mysql --host "$DB_HOST" --user "$DB_USER" -p"$DB_PASS" "$DB_NAME"'  
+      ;;
+    postgres)
+      passthru $COMPOSE_BIN exec console bash -c 'PGPASSWORD="$DB_PASS" psql --host="$DB_HOST" --username="$DB_USER" --dbname="$DB_NAME"'
+      ;;
+    *)
+      echo "error: database.platform attribute value '${DB_PLATFORM}' not supported" >&2
+      exit 1
+      ;;
+    esac
 
 command('assets download'):
   env:
